export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  AUTH_CALLBACK: "/auth/callback",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  JOBS: "/jobs",
  JOB_DETAIL: (id: string) => `/jobs/${id}`,
  COMPANIES: "/companies",
  COMPANY_DETAIL: (id: string) => `/companies/${id}`,
  PROFILE: "/profile",
  ONBOARDING: "/onboarding",
  DASHBOARD: "/dashboard",
  CV_LIST: "/cv",
  CV_NEW: "/cv/new",
  CV_EDIT: (id: string) => `/cv/${id}/edit`,
  APPLICATIONS: "/applications",
  SAVED_JOBS: "/saved-jobs",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  SAVED_SEARCHES: "/saved-searches",
  RECRUITER_COMPANY: "/recruiter/company",
  RECRUITER_JOBS: "/recruiter/jobs",
  RECRUITER_JOB_NEW: "/recruiter/jobs/new",
  RECRUITER_JOB_EDIT: (jobId: string) => `/recruiter/jobs/${jobId}/edit`,
  RECRUITER_JOB_APPLICATIONS: (jobId: string) => `/recruiter/jobs/${jobId}/applications`,
  ADMIN_USERS: "/admin/users",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_ROLE_DETAIL: (id: string) => `/admin/roles/${id}`,
  ADMIN_CATEGORIES: "/admin/categories",
} as const;
