export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  JOBS: "/jobs",
  JOB_DETAIL: (id: string) => `/jobs/${id}`,
  COMPANIES: "/companies",
  COMPANY_DETAIL: (id: string) => `/companies/${id}`,
  PROFILE: "/profile",
  CV_LIST: "/cv",
  CV_NEW: "/cv/new",
  CV_EDIT: (id: string) => `/cv/${id}/edit`,
  APPLICATIONS: "/applications",
  SAVED_JOBS: "/saved-jobs",
  MESSAGES: "/messages",
  RECRUITER_JOB_APPLICATIONS: (jobId: string) => `/recruiter/jobs/${jobId}/applications`,
} as const;
